data:
  amino_acids:
    encoding: onehot
    symbol: [A, R, 'N', D, C, E, Q, G, H, I, L, K, M, F, P, S, T, U, W, 'Y', V]
  modifications:
    fixed: ['cC']
    encoding: atoms
    element: [H, C, 'N', O, P, S]
  monosaccharides:
    encoding: onehot
    symbol: [H, 'N', A, G, F]
  charge: True

  peptide_fragments:
    fragment_type: ['b', 'y']
    fragment_charge: [1, 2]
    loss_type: []
    fragment_glycan: ['$', 'N(1)']
    other: ignore
  glycan_fragments:
    fragment_type: ['Y']
    fragment_charge: [1, 2, 3]
    other: ignore

model:
  type: 'GlycoPeptideMS2TreeLSTM'
  hyperparams:
    charge_dim: 2
    pep_lstm_hidden_size: 256
    pep_lstm_num_layers: 2
    pep_dropout: 0.25
    gly_lstm_hidden_size: 256
    gly_lstm_num_layers: 1
    gly_dropout: 0.25

training:
  batch_size: 16
  lr: 0.0001
  warmup: 0
  scheduler:
    type: "ReduceLROnPlateau"
    args:
      patience: 5


