data:
  amino_acids:
    encoding: onehot
    symbol: [A, R, 'N', D, C, E, Q, G, H, I, L, K, M, F, P, S, T, U, W, 'Y', V]
  modifications:
    fixed: ['cC']
    encoding: atoms
    element: [H, C, 'N', O, P, S]

model:
  type: 'PeptideRTBiLSTM'
  hyperparams:
    lstm_hidden_size: 256
    lstm_num_layers: 2
    dropout: 0.25

training:
  batch_size: 64
  lr: 0.001
  warmup: 5
  scheduler:
    type: "CosineAnnealingWarmRestarts"
    args:
      T_0: 45
      T_mult: 2
